version: '3'
volumes:
  data:
services:
  db:
    image: postgres:9.6
    volumes:
      # data volume
      - data:/var/lib/postgres/data
      # scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    image: nginx:1.13
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
      # Configure reverse proxy
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  app:
    image: python:3.6
    volumes:
      # App
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh